### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by tsukijin** [Brychlikov/pywal_sublime#1]
hi, appreciate the effort but how exactly do I 'install' and use this script?

**Comment by Shaqundalond** [comment]
1. clone it somewhere
2. (optional) copy the script to your path (makes it easier with execution)
3. Add the following line to your user Preferences in Sublime (Preferences / Settings )
`"color_scheme": "Packages/User/PyWal.sublime-color-scheme",`
4. whenever you run the wal command make sure to also run the script.

**Comment by Brychlikov** [comment]
Sorry for the delay, I have now added usage info to README
